spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kim
    password: 8531
    url: jdbc:mysql://localhost:3306/restApiPractice?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
