spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue:
            org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  profiles:
    include: oauth
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
    store-type: jdbc
server:
  servlet:
    encoding:
      force-response: true

